### ISSUE TITLE
Ability to instantiate Bundle class from links.json in TDR snapshot

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/hca-metadata-api#12] opened 2020-05-04 21:38 UTC

**Comment by theathorn** [comment] 2020-05-21 18:52
Hannes to close and create replacement ticket in Azul.

**Comment by melainalegaspi** [comment] 2020-05-28 20:59
Duplicate of DataBiosphere/hca-metadata-api#15

**Closed as completed by melainalegaspi** 2020-05-28 20:59 UTC
Labels: duplicate, orange
